

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
 
 
CREATE SCHEMA IF NOT EXISTS `facilmigra` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE 'facilmigra'
CREATE TABLE IF NOT EXISTS `facilmigra`.`CARGOS` (
  `ID_CARGO` INT(11) NOT NULL,
  `NOME_CARGO` VARCHAR(45) NOT NULL,
  `CANDIDATOS_ID_CARGO` INT(11) NOT NULL,
  PRIMARY KEY (`ID_CARGO`, `CANDIDATOS_ID_CARGO`),
  INDEX `fk_CARGOS_CANDIDATOS_idx` (`CANDIDATOS_ID_CARGO` ASC) VISIBLE,
  CONSTRAINT `fk_CARGOS_CANDIDATOS`
    FOREIGN KEY (`CANDIDATOS_ID_CARGO`)
    REFERENCES `facilmigra`.`CANDIDATOS` (`ID_CARGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
 
CREATE TABLE IF NOT EXISTS `facilmigra`.`CANDIDATOS` (
  `ID_CARGO` INT(11) NOT NULL,
  `ID_CANDIDATO` VARCHAR(45) NOT NULL,
  `NOME_CANDIDATO` VARCHAR(45) NULL DEFAULT NULL,
  `DATA_NASC_CANDIDATO` DATE NULL DEFAULT NULL,
  `CPF_CANDIDATO` VARCHAR(45) NOT NULL,
  `CONTATO_CANDIDATO` VARCHAR(45) NOT NULL,
  `ENDERCO_CANDIDATO` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CARGO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
 
CREATE TABLE IF NOT EXISTS `facilmigra`.`EMPRESAS` (
  `ID_EMPRESA` INT(11) NOT NULL,
  `CNPJ_EMPRESA` VARCHAR(45) NOT NULL,
  `RAZAO_SOCIAL` VARCHAR(45) NOT NULL,
  `ENDERECO_EMPRESA` VARCHAR(45) NOT NULL,
  `CEP_EMPRESA` VARCHAR(45) NOT NULL,
  `UF_EMPRESA` VARCHAR(45) NOT NULL,
  `VAGAS_ID_VAGA` INT(11) NOT NULL,
  PRIMARY KEY (`ID_EMPRESA`, `VAGAS_ID_VAGA`),
  UNIQUE INDEX `CNPJ_EMPRESA_UNIQUE` (`CNPJ_EMPRESA` ASC) VISIBLE,
  UNIQUE INDEX `CEP_EMPRESA_UNIQUE` (`CEP_EMPRESA` ASC) VISIBLE,
  UNIQUE INDEX `UF_EMPRESA_UNIQUE` (`UF_EMPRESA` ASC) VISIBLE,
  INDEX `fk_EMPRESAS_VAGAS1_idx` (`VAGAS_ID_VAGA` ASC) VISIBLE,
  CONSTRAINT `fk_EMPRESAS_VAGAS1`
    FOREIGN KEY (`VAGAS_ID_VAGA`)
    REFERENCES `facilmigra`.`VAGAS` (`ID_VAGA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
 
CREATE TABLE IF NOT EXISTS `facilmigra`.`VAGAS` (
  `ID_VAGA` INT(11) NOT NULL,
  `DESCRICAO_VAGA` VARCHAR(45) NULL DEFAULT NULL,
  `CARGA_HORARIO` VARCHAR(45) NULL DEFAULT NULL,
  `ID_EMPRESA` VARCHAR(45) NULL DEFAULT NULL,
  `ID_CONTRATO` VARCHAR(45) NULL DEFAULT NULL,
  `CONTRATOS_ID_CONTRATO` INT(11) NOT NULL,
  PRIMARY KEY (`ID_VAGA`, `CONTRATOS_ID_CONTRATO`),
  INDEX `fk_VAGAS_CONTRATOS1_idx` (`CONTRATOS_ID_CONTRATO` ASC) VISIBLE,
  CONSTRAINT `fk_VAGAS_CONTRATOS1`
    FOREIGN KEY (`CONTRATOS_ID_CONTRATO`)
    REFERENCES `facilmigra`.`CONTRATOS` (`ID_CONTRATO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
 
CREATE TABLE IF NOT EXISTS `facilmigra`.`CONTRATOS` (
  `ID_CONTRATO` INT(11) NOT NULL,
  `TIPO_CONTRATO` VARCHAR(45) NOT NULL,
  `TEMPO_CONTRATO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_CONTRATO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
 
 
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;